<?php
$xpdo_meta_map['ShortlinkMgrLink'] = array(
    'package'   => 'shortlinkmgr',
    'version'   => '1.0',
    'table'     => 'shortlinkmgr_links',
    'extends'   => 'xPDOSimpleObject',
    'fields'    => array(
        'shortcode'         => '',
        'title'             => '',
        'description'       => null,
        'published'         => 1,
        'redirect_id'       => null,
        'redirect_url'      => null,
        'redirect_type'     => 302,
        'utm_source'        => null,
        'utm_medium'        => null,
        'utm_campaign'      => null,
        'utm_term'          => null,
        'utm_content'       => null,
        'anchor'            => null,
        'additional_params' => null,
        'click_count'       => 0,
        'expires_at'        => null,
        'created_by'        => 0,
        'created_at'        => null,
        'updated_at'        => null,
    ),
    'fieldMeta' => array(
        'shortcode'         => array('dbtype' => 'varchar',  'precision' => '32',   'phptype' => 'string',   'null' => false, 'default' => '', 'index' => 'unique'),
        'title'             => array('dbtype' => 'varchar',  'precision' => '255',  'phptype' => 'string',   'null' => true,  'default' => ''),
        'description'       => array('dbtype' => 'text',                            'phptype' => 'string',   'null' => true),
        'published'         => array('dbtype' => 'tinyint',  'precision' => '1',    'phptype' => 'integer',  'null' => false, 'default' => 1),
        'redirect_id'       => array('dbtype' => 'int',      'precision' => '10',   'phptype' => 'integer',  'null' => true),
        'redirect_url'      => array('dbtype' => 'varchar',  'precision' => '2048', 'phptype' => 'string',   'null' => true),
        'redirect_type'     => array('dbtype' => 'int',      'precision' => '3',    'phptype' => 'integer',  'null' => false, 'default' => 302),
        'utm_source'        => array('dbtype' => 'varchar',  'precision' => '255',  'phptype' => 'string',   'null' => true),
        'utm_medium'        => array('dbtype' => 'varchar',  'precision' => '255',  'phptype' => 'string',   'null' => true),
        'utm_campaign'      => array('dbtype' => 'varchar',  'precision' => '255',  'phptype' => 'string',   'null' => true),
        'utm_term'          => array('dbtype' => 'varchar',  'precision' => '255',  'phptype' => 'string',   'null' => true),
        'utm_content'       => array('dbtype' => 'varchar',  'precision' => '255',  'phptype' => 'string',   'null' => true),
        'anchor'            => array('dbtype' => 'varchar',  'precision' => '255',  'phptype' => 'string',   'null' => true),
        'additional_params' => array('dbtype' => 'text',                            'phptype' => 'string',   'null' => true),
        'click_count'       => array('dbtype' => 'int',      'precision' => '10',   'phptype' => 'integer',  'null' => false, 'default' => 0),
        'expires_at'        => array('dbtype' => 'datetime',                        'phptype' => 'datetime', 'null' => true),
        'created_by'        => array('dbtype' => 'int',      'precision' => '10',   'phptype' => 'integer',  'null' => false, 'default' => 0),
        'created_at'        => array('dbtype' => 'datetime',                        'phptype' => 'datetime', 'null' => true),
        'updated_at'        => array('dbtype' => 'datetime',                        'phptype' => 'datetime', 'null' => true),
    ),
    'indexes'   => array(
        'PRIMARY'   => array(
            'alias'   => 'PRIMARY', 'primary' => true, 'unique' => true, 'type' => 'BTREE',
            'columns' => array('id' => array('length' => '', 'collation' => 'A', 'null' => false)),
        ),
        'shortcode' => array(
            'alias'   => 'shortcode', 'primary' => false, 'unique' => true, 'type' => 'BTREE',
            'columns' => array('shortcode' => array('length' => '', 'collation' => 'A', 'null' => false)),
        ),
    ),
    'composites' => array(
        'Clicks' => array(
            'class'       => 'ShortlinkMgrClick',
            'local'       => 'id',
            'foreign'     => 'link_id',
            'cardinality' => 'many',
            'owner'       => 'local',
        ),
    ),
);
